payload:
  artifacts:
    - name: hideconsole
      type: evasion
    - name: aes
      type: encoder
      args:
        - name: Key
          value: "dNJFi4GmAl9rz3CqBpftNoJy"
    - name: reverse-order
      type: encoder
    - name: windows/native/local/SpfGateCreateThread
      type: injector
  #sgn: false #must be decommented in the code to be used
  type: exe
  arch: x64
  debug: false
  obfuscation: true #need garble to be installed

